### ISSUE TITLE
missing.dll file

### ISSUE THREAD

**Issue by LoneWolfGmer** [Lillious/Lethal-Company-Mod-Library#4]
as the title says. I can't find the .dll file you mentioned in the readme file. 

![image](https://github.com/Lillious/Lethal-Company-Mod-Library/assets/37723026/602cbe1d-5024-4247-b224-a89d5fe0e902)
 maybe it's hindsight on your part or something who knows? but without the file you mentioned I have nothing to put in the thing XD for the mods folder

**Comment by Lillious** [comment]
You have to build the project in visual studio manually until a dll file is provided under releases. The project is undergoing rapid changes.

**Comment by LoneWolfGmer** [comment]
Might be a good idea to mention this in the directions
