### ISSUE TITLE
directions for how to config the mod ingame.

### ISSUE THREAD

**Issue by LoneWolfGmer** [Lillious/Lethal-Company-Mod-Library#9]
I tried to figure out if it's supposed to be able to be controlled ingame or not. but either way, I tried with no luck. so is it supposed to be able to be tweaked ingame or what?

**Comment by Elyriand21** [comment]
The mod library has no in-game use. This is a library that has methods that interact with the game's code directly to aid modders in minimizing the amount of code they write while also being able to be more direct in their language.

The library would be used as a [dependency](https://www.sonatype.com/launchpad/what-are-software-dependencies#:~:text=dependency%20at%20scale%3F-,What%20is%20a%20software%20dependency%3F,application%20depends%20on%20that%20library.)

**Comment by Lillious** [comment]
@LoneWolfGmer for any future questions I would highly recommend you @ me in the Lethal Company Discord as responses here are going to take a really long time for me to get to.
Discord: https://discord.gg/g5aeZbTv7u
